### PR TITLE
contribution of a new loss function for squared Hellinger distance

### PR DESCRIPTION
**Pull request by brandmaier**

### CODE REVIEW

**Review by Maximilian-Stefan-Ernst — CHANGES_REQUESTED** [review]
Before merging, we need to
- [ ] write tests
- [ ] add documentation
- [ ] make the use of a meanstructure optional
- [ ] maybe add analytic gradients
- [ ] export the relevant types and methods

@aaronpeikert should we make a feature branch, merge the pull request to that branch and continue there?

**Comment by aaronpeikert** [comment]
> @aaronpeikert should we make a feature branch, merge the pull request to that branch and continue there?

The only way to rename the source branch is to create a new PR + branch. From my side its ok to treat this as a feature branch though it does not conform to naming guidelines to keep the history (which would be lost in the new PR).

**Comment by aaronpeikert** [comment]
Let's merge #135 and #137 then try out the reopening of PRs with #133.

**Comment by Maximilian-Stefan-Ernst** [comment]
I dont understand the problem. I can just create a feature/hellinger branch from devel and redirect the pull request there (I already changed it from main to devel).

**Comment by Maximilian-Stefan-Ernst** [comment]
Okay, I changed the base to feature/hellinger, would merge now and continue working on that branch

**Comment by aaronpeikert** [comment]
:+1:

**Pull request merged**
